export const LOG_IN = 'LOG_IN';

export const SET_COLOR = 'SET_COLOR';
export const SET_THICKNESS = 'SET_THICKNESS';
export const SET_TOOL = 'SET_TOOL';
export const SET_CLEAR = 'SET_CLEAR';

export const DRAW_STROKE = 'DRAW_STROKE';
export const UNDO_STROKE = 'UNDO_STROKE';
export const REDO_STROKE = 'REDO_STROKE';

export const TRUNCATE = 'TRUNCATE';

export const SET_STROKES = 'SET_STROKES';
export const DELETE_STROKES = 'DELETE_STROKES';
export const SET_SELECTED_STROKE = 'SET_SELECTED_STROKE';
export const CLEAR_CANVAS = 'CLEAR_CANVAS';
export const CHANGE_CANVAS = 'CHANGE_CANVAS';
export const SET_SAVE_CURRENT_CANVAS = 'SET_SAVE_CURRENT_CANVAS';
export const CLEAR_BLACKBOARDS = 'CLEAR_BLACKBOARDS';

export const SET_TEMP_ANIMATION = 'SET_TEMP_ANIMATION';
