export const LOG_IN = 'LOG_IN';
export const SET_COLOR = 'SET_COLOR';
export const SET_THICKNESS = 'SET_THICKNESS';
export const SET_TOOL = 'SET_TOOL';
export const SET_CLEAR = 'SET_CLEAR';
export const DRAW_STROKE = 'DRAW_STROKE';
export const UNDO_STROKE = 'UNDO_STROKE';
export const REDO_STROKE = 'REDO_STROKE';
export const TRUNCATE = 'TRUNCATE';
export const SAVE_CANVAS = 'SAVE_CANVAS';
//# sourceMappingURL=mutation-types.js.map